<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tla</string>
	</array>
	<key>name</key>
	<string>TLA</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\\\*.*$</string>
			<key>name</key>
			<string>comment.line.slash-star</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\={4,}</string>
			<key>name</key>
			<string>markup.other.startbreak</string>
		</dict>
		<dict>
			<key>match</key>
			<string>={4,}</string>
			<key>name</key>
			<string>markup.other.endbreak</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\\h[0-9a-fA-F]+|\\o[0-9]+|\\b[01]+|\d+\.\d+|\d+)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b==\b</string>
			<key>name</key>
			<string>keyword.operator.definition.tla</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\/\\|\\\/|\=&gt;|&lt;\=&gt;|\|\=|\=\||\|\-|\-\||~)</string>
			<key>name</key>
			<string>keyword.operator.logic.tla</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;\=|&gt;\=|\=|&lt;|&gt;|\/\=|\#</string>
			<key>name</key>
			<string>keyword.operator.comparison.tla</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b=\b</string>
			<key>name</key>
			<string>keyword.operator.assignment.tla</string>
		</dict>
        <dict>
			<key>match</key>
			<string>(\\EE|\\AA)</string>
			<key>name</key>
			<string>keyword.operator.temporal.quantification.tla</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\\E|\\A)</string>
			<key>name</key>
			<string>keyword.operator.quantification.tla</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\\notin|:)</string>
			<key>name</key>
			<string>keyword.operator.sets.tla</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\|\-&gt;|\-&gt;)</string>
			<key>name</key>
			<string>keyword.operator.functions.tla</string>
		</dict>
        <dict>
			<key>match</key>
			<string>\\(approx|asymp|bigcirc|bullet|cap|cdot|circ|cong|cup|div|doteq|equiv|geq|gg|in|intersect|land|leq|ll|lor|o|odot|ominus|oplus|oslash|otimes|prec|preceq|propto|sim|simeq|sqcap|sqcup|sqsubset|sqsubseteq|sqsupset|sqsupseteq|star|subset|subseteq|succ|succeq|supset|supseteq|union|uplus|wr)\b</string>
			<key>name</key>
			<string>keyword.operator.latex.tla</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\+|\-|\*|\/){1}\b</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.tla</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[\]|\&lt;\&gt;|\-\+\-&gt;)</string>
			<key>name</key>
			<string>keyword.operator.temporal.tla</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#reserved-words</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.tla</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>';
			end = '</string>
			<key>name</key>
			<string>string.quoted.single.tla</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.begin.tla</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.end.tla</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.list.tla</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\[|\,)\s*(?![\],])</string>
					<key>contentName</key>
					<string>meta.structure.list.item.tla</string>
					<key>end</key>
					<string>\s*(?:(,)|(?=\]))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.list.tla</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tuple.begin.tla</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.empty-tuple.tla</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tuple.end.tla</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&lt;&lt;)(\s*(&gt;&gt;))</string>
			<key>name</key>
			<string>meta.structure.tuple.tla</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>reserved-words</key>
		<dict>
			<key>match</key>
			<string>\b(ACTION|ASSUME|ASSUMPTION|AXIOM|BY|CASE|CHOOSE|CONSTANT|CONSTANTS|COROLLARY|DEF|DEFINE|DEFS|DOMAIN|ELSE|ENABLED|EXCEPT|EXTENDS|HAVE|HIDE|IF|IN|INSTANCE|LAMBDA|LEMMA|LET|LOCAL|MODULE|NEW|OBVIOUS|OMITTED|ONLY|OTHER|PICK|PROOF|PROPOSITION|PROVE|QED|RECURSIVE|SF_|STATE|SUBSET|SUFFICES|TAKE|TEMPORAL|THEN|THEOREM|UNCHANGED|UNION|USE|VARIABLE|VARIABLES|WF_|WITH|WITNESS)\b</string>
			<key>name</key>
			<string>keyword.control.tla</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.tla</string>
	<key>uuid</key>
	<string>A29E70ED-6D0F-4997-84E9-528B8EC412A1</string>
</dict>
</plist>
